### ISSUE TITLE
Enahnce TX Retry & Timeout Strategies

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana-ping-api#1]
## Issue
On Sunday, Apr 10 around 12:00 UTC, the cluster is running well, but the Solana Ping Stats chart shows many errors.

<img width="1127" alt="Screen Shot 2022-04-10 at 6 00 37 AM" src="https://user-images.githubusercontent.com/79186/162617051-75cc018d-5f05-467e-aea8-fb06b8b4b60e.png">

In comparison, the validators.app Ping Thing shows average confirmation times, from 3 points on the cluster, of around 5 seconds.

<img width="1248" alt="Screen Shot 2022-04-10 at 6 01 28 AM" src="https://user-images.githubusercontent.com/79186/162617139-166a3916-15a3-4e2a-9e21-3856513bcf3d.png">

Source: https://www.validators.app/ping-thing

I believe the low success rate shown on the explorer is due to the TX retry strategies used on the ping client or the RPC node.

A TX is valid for up to 150 blocks after the submitted block hash. -- about 60-75 seconds on a wall clock. So, the 35-second `WaitConfirmationTimeout` threshold may be too short (depending on your retry strategy).

## Suggestion
- Retry TXs from the client or the RPC node every 2 seconds until confirmation or the block hash expires.
- Increase `WaitConfirmationTimeout` to 60 or 75 seconds (or rely on the block hash expiration error).

**Comment by pieceofr** [comment]
Thanks for feedback. 
We have changed WaitConfirmationTimeout to 60sec and we are investigating our ping retry.
